//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundManagerDashboard.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FundManagerDashboard.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddPanelAdd {
            get {
                return ResourceManager.GetString("AddPanelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an &apos;Equity&apos; or &apos;Bond&apos; stock to my Fund.
        /// </summary>
        public static string AddPanelHeader {
            get {
                return ResourceManager.GetString("AddPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string AddPanelStockPrice {
            get {
                return ResourceManager.GetString("AddPanelStockPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter price.
        /// </summary>
        public static string AddPanelStockPriceWaterMark {
            get {
                return ResourceManager.GetString("AddPanelStockPriceWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string AddPanelStockQuantity {
            get {
                return ResourceManager.GetString("AddPanelStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter quantity.
        /// </summary>
        public static string AddPanelStockQuantityWaterMark {
            get {
                return ResourceManager.GetString("AddPanelStockQuantityWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock type:.
        /// </summary>
        public static string AddPanelStockType {
            get {
                return ResourceManager.GetString("AddPanelStockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketValue.
        /// </summary>
        public static string ListHeaderMarketValue {
            get {
                return ResourceManager.GetString("ListHeaderMarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ListHeaderName {
            get {
                return ResourceManager.GetString("ListHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ListHeaderPrice {
            get {
                return ResourceManager.GetString("ListHeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ListHeaderQuantity {
            get {
                return ResourceManager.GetString("ListHeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockWeight.
        /// </summary>
        public static string ListHeaderStockWeight {
            get {
                return ResourceManager.GetString("ListHeaderStockWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionCost.
        /// </summary>
        public static string ListHeaderTransactionCost {
            get {
                return ResourceManager.GetString("ListHeaderTransactionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ListHeaderType {
            get {
                return ResourceManager.GetString("ListHeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Summary.
        /// </summary>
        public static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalMarketValue.
        /// </summary>
        public static string SummaryTotalMarketValue {
            get {
                return ResourceManager.GetString("SummaryTotalMarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalNumber.
        /// </summary>
        public static string SummaryTotalNumber {
            get {
                return ResourceManager.GetString("SummaryTotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalStockWeight.
        /// </summary>
        public static string SummaryTotalStockWeight {
            get {
                return ResourceManager.GetString("SummaryTotalStockWeight", resourceCulture);
            }
        }
    }
}
